Add the feature to add the prefix to namespace.
mkaring/ConfuserEx pull request #280
Opened 2020-12-23 03:39 UTC by iamwangxi

In use, different products need to be obfuscated. If the obfuscated namespaces are the same, conflicts will occur. Therefore, it is necessary to add different prefixes during obfuscation. This submission adds the function of passing in prefixes from the command line.

2020-12-23 09:55 UTC, mkaring commented
I don't understand the use case for this change. What would create such a namespace collision in a way that matters?

2020-12-24 09:36 UTC, iamwangxi commented
> I don't understand the use case for this change. What would create such a namespace collision in a way that matters?

For example, the project ProjectA refers to two dll files, p1.dll and p2.dll, both of which are obfuscated by ConfuserEx. If a namespace in p1.dll is obfuscated with _n, and a namespace in p2.dll is obfuscated with _n (although the probability is very low), then the project cannot be compiled. The purpose of this function is to prevent this.

2020-12-24 09:58 UTC, mkaring commented
There is no issue in having the same namespace in multiple assemblies.
Usually ConfuserEx only renames types that are `internal` to the assembly. `public` types keep their name and the namespace declaration.

The use case you are describing would only occur in case you are renaming `public` members and use the assembly to compile the file application, after the obfuscation is done. This has the extremely slim chance of producing two types with the exact same full name in two different assemblies. But this case does not matter, because you can't use the assembly to compile the final application anyway, because the name you have to use the in code is illegal in all .NET languages (except MSIL) and it's random.

I really need a clear use case here to  understand the potential issue. If you can produce a small example that showcases the issue, that may be helpful. You can set the rename mode to debug or set the flatten parameter to easily produce the same namespace in two different assemblies.

2020-12-25 04:21 UTC, iamwangxi commented
> There is no issue in having the same namespace in multiple assemblies.
> Usually ConfuserEx only renames types that are `internal` to the assembly. `public` types keep their name and the namespace declaration.
> 
> The use case you are describing would only occur in case you are renaming `public` members and use the assembly to compile the file application, after the obfuscation is done. This has the extremely slim chance of producing two types with the exact same full name in two different assemblies. But this case does not matter, because you can't use the assembly to compile the final application anyway, because the name you have to use the in code is illegal in all .NET languages (except MSIL) and it's random.
> 
> I really need a clear use case here to understand the potential issue. If you can produce a small example that showcases the issue, that may be helpful. You can set the rename mode to debug or set the flatten parameter to easily produce the same namespace in two different assemblies.

Let me explain in detail. In the process of using, there are some methods that are only called internally, but they are also written as public. Such methods also need to be obfuscated (in rename protection, we need to enable renPublic). In this way, if a certain namespace in two dll files is obfuscated with the same name, and a certain struct is also obfuscated with the same name, then a project that contains both dll files cannot use this struct correctly.
Take the code I uploaded as an example. Under namespace=namespace_conflict, there is a public struct called test. Use this code to compile two dlls. In a project that calls these two dlls at the same time, new test() will report an error "Error	CS0433	The type 'test' exists in both 'namespace_conflict, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'namespace_conflict2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	conflict_test".
In fact, a similar situation did occur in a certain obfuscation. The namespaces of the two products were obfuscated with the same name, and there happened to be a public struct under it that was also obfuscated with the same name. We re-executed obfuscation to solve this problem.
If the namespace has a prefix, it can be guaranteed that there will be no conflicts. In this case, if the class name conflicts, we can solve this problem by adding namespace when calling. For example, the two namespaces are N1 and N2, and there is a public struct called test under them. To call test in N1, just execute new N1.test().
The prefix function is supported in other .NET obfuscation tools, such as deepsea and dotfuscator (https://www.preemptive.com/dotfuscator/ce/docs/help/obfuscation_renaming.html).
The code used to make dll and used to execute the code shown below.
``` C#
// this file is used to make dll file

namespace namespace_conflict {
    public struct test {
        public void testconflict() {

    }
  }
}
```

``` C#
// This file is used to execute
using namespace_conflict;

namespace test_conflict {
  class test_conflict_class {
    static void Main(string[] args) {
      new test();
    }
  }
}
```

2020-12-25 11:44 UTC, mkaring commented
I understand that the conflict may lead to a *compiler* error, the question is why are you using the compiler after the obfuscation is already done and you also reference obfuscated types?

This means that you would have to change the *code* of the executable every time the assemblies are obfuscated again, because the names are random.

Wouldn't it be a much cleaner way to go about this to just disable the renaming for the specific types you need to reference by code that is compiled later? You already have to limit to limit the renaming mode to letters in order to get this working.

2020-12-28 01:41 UTC, iamwangxi commented
> I understand that the conflict may lead to a _compiler_ error, the question is why are you using the compiler after the obfuscation is already done and you also reference obfuscated types?
> 
> This means that you would have to change the _code_ of the executable every time the assemblies are obfuscated again, because the names are random.
> 
> Wouldn't it be a much cleaner way to go about this to just disable the renaming for the specific types you need to reference by code that is compiled later? You already have to limit to limit the renaming mode to letters in order to get this working.

Sorry for not making it clear before: Our company’s products are in the form of dll files, and customers use our dll files to compile their products (that is, the first paragraph of code at the end of the previous reply is our product, and the second paragraph is Client's), so we don't know the mode of client program. Our product code is constantly updated. After each update and recompilation, the obfuscation needs to be re-executed. It is very troublesome to check whether the obfuscated dll has conflicts each time. We hope to directly avoid this possibility through the prefix.

2020-12-28 12:35 UTC, mkaring commented
I understand that. By why are the parts the customer code needs to reference being renamed at all? Doesn't that mean that the customer needs to alter the code for every new version of the product, due to the change of the namespaces? That sounds like a major hassle for your client. This is the reason why the `public` types and members are usually excluded from the `rename` obfuscation.

Don't get me, I'm in general not opposed to this change. I won't merge it in as a command line paramater, because that is not where this option belongs, but rather as a parameter for the `rename` protection, so it can be setup in the `*.crproj` file and with the declarative obfuscation.

2020-12-28 12:40 UTC, mkaring requested changes
The prefix does not belong to the command line options. The proper way to implement this, is as an option to the `rename` protection, like the [`renPdb`][1] for example. This way it can be properly setup in the project file and in the declarative obfuscation.

In addition it would be more flexible to implement this as a "namespace format" instead of a prefix. This format should just be used with `String.Format(namespaceFormat, randomNsName)`. This way the format can be used as prefix, suffix or both.

[1]: https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/RenamePhase.cs#L49

2020-12-29 09:40 UTC, iamwangxi commented
> The prefix does not belong to the command line options. The proper way to implement this, is as an option to the `rename` protection, like the [`renPdb`](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/RenamePhase.cs#L49) for example. This way it can be properly setup in the project file and in the declarative obfuscation.
> 
> In addition it would be more flexible to implement this as a "namespace format" instead of a prefix. This format should just be used with `String.Format(namespaceFormat, randomNsName)`. This way the format can be used as prefix, suffix or both.

You are right. The prefix function should belong to a setting of named protection, not a command line. This setting can indeed solve our problem. Thank you very much!

2020-12-30 04:04 UTC, iamwangxi commented
> The prefix does not belong to the command line options. The proper way to implement this, is as an option to the `rename` protection, like the [`renPdb`](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/RenamePhase.cs#L49) for example. This way it can be properly setup in the project file and in the declarative obfuscation.
> 
> In addition it would be more flexible to implement this as a "namespace format" instead of a prefix. This format should just be used with `String.Format(namespaceFormat, randomNsName)`. This way the format can be used as prefix, suffix or both.

This feature is very important to us, and we look forward to its realization soon. Thanks again!

2020-12-31 15:32 UTC, mkaring commented
This pull request is closed in favor of #286

2020-12-31 15:32 UTC, closed without merging