Renaming fixes and improvements
mkaring/ConfuserEx pull request #305
Opened 2021-01-17 17:40 UTC by KvanTTT

* Rename overloaded methods to different names, add tests, fix #293
* Incorrect symbol map generating for nested classes if decodable is activated, fix #296
* Remove not used code
* Decrease number of allocations in renaming modules, improve performance
* Extract MessageDeobfuscator from UI app, add tests

2021-01-17 20:01 UTC, mkaring requested changes
I don't think the increase in size is much of an issue. If someone wants to store the file, it can just be compressed. Even deflate should yield good results for those mapping files.

There are two changes you did, I strongly disagree with.

1. You added the `[Flags]`-Attribute to the renamer modes. This is simply wrong. This enum represents fixed values and not flags. You can't combine those values in any meaningful way.
2. The changes you did in the naming introduce a major change how generic types are handled. This will introduce problems. Please revert this part or change it to ensure that the generic name convention remains.

2021-01-17 21:37 UTC, ElektroKill commented
Would it be possible to make the feature from issue https://github.com/mkaring/ConfuserEx/issues/293 toggleable? This would improve customizability of the renaming protection, also some people may want to use the old renaming behavior.

2021-01-18 09:38 UTC, KvanTTT commented on Confuser.Renamer/RenameMode.cs
> +	[Flags]
Because Rider warned about it on [this line](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/NameService.cs#L263). It's treated as `Flags`, see [RenameMode](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/RenameMode.cs#L16-L18) declaration.

2021-01-18 09:39 UTC, KvanTTT commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
Could you provide a test sample that reproduces such an error? I think it can be fixed in a more proper way.

2021-01-18 09:42 UTC, KvanTTT commented
@ElektroKill the old renaming behavior is not fully correct because of #296. Also, it makes testing more complicated. I'll take a look at how it's complex to support both behaviors.

2021-01-18 09:44 UTC, KvanTTT commented
> I don't think the increase in size is much of an issue. If someone wants to store the file, it can just be compressed. Even deflate should yield good results for those mapping files.

Yes, I also think that's not a problem. I just reported the change before and after improvements.

2021-01-18 10:46 UTC, mkaring commented on Confuser.Renamer/RenameMode.cs
> +	[Flags]
The line you marked is wrong. You can't mix the the values as flags. It should be
```cs
if (mode == RenameMode.Decodable)
```

2021-01-18 10:48 UTC, mkaring commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
This may take some time. I don't remember exactly how to produce this issue. I'm fairly certain that is was related to using the type parameters in WPF.

2021-01-18 10:56 UTC, KvanTTT commented on Confuser.Renamer/RenameMode.cs
> +	[Flags]
Actually not only `Decodable`, but `Sequential` too:

```cs
if (mode == RenameMode.Decodable || mode == RenameMode.Sequential)
```

2021-01-18 10:58 UTC, mkaring commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
Preserving the generics count was originally introduced for this issue: yck1509#463
This issue points to problems when using the protected assembly as reference in Visual Studio. Sadly there are very limited information on this.

There was also the issue #161 that was related to those generic values, how ever the unit test for this issue still passes, so this seems to be okay.

2021-01-18 11:10 UTC, KvanTTT commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
> This causes errors in some systems such as Visual Studio 2015 when building for the Windows 10 Universal target.

It sounds like outdated stuff. Maybe just leave it as is and fix it if somebody reports a bug? The current implementation looks like a workaround.

2021-01-18 15:17 UTC, KvanTTT commented
I've added `shortNames` parameter that is `false` by default, please test.

2021-01-18 16:16 UTC, mkaring commented
> I've added `shortNames` parameter that is `false` by default, please test.

I think you added a parameter for the wrong function. The feature to toggle is #293 (overload methods with different names) and not #296

2021-01-18 16:18 UTC, KvanTTT commented
They are related: short names automatically disable methods overloading and vice versa.

2021-01-20 15:52 UTC, KvanTTT commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
@mkaring what do you think about it?

2021-02-12 21:14 UTC, mkaring commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
The issue with this change is, that I do not know the scope of effects this has. This will require extensive testing against different targets. This change was introduced for a specific issue. Back than there were no unit tests that showcase the issues.

One example is that a generic type that lacks the backtick can't be used in WPF anymore. Resolving the generic type doesn't fail if the backtick is missing, but while restoring the name it ends up here:
[Reference Source - CodeTypeReference](https://referencesource.microsoft.com/#System/compmod/system/codedom/CodeTypeReference.cs,334)

At this point it tries to restore the "proper" name of the type and fails.

Something very similar happens, in case there is a stray backtick in the name. But in this case the inital parsing of the name fails. This may be caused by the "ASCII" naming. This is the main reason why I added the "reflection" naming mode.

2021-02-13 11:29 UTC, KvanTTT commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
So, you insist on returning the old behavior?

2021-02-13 11:43 UTC, mkaring commented on Confuser.Renamer/NameService.cs
> -			name = ParseGenericName(name, out var count);
Either that, or it's controllable by a parameter.

2021-06-17 15:45 UTC, KvanTTT commented
Any chance this request will be merged? Should I resolve conflicts?

2021-06-23 22:38 UTC, mkaring commented
@KvanTTT: Please resolve the conflicts. I'll merge it.

2021-06-27 13:15 UTC, KvanTTT commented
Done. Also, I fixed the bug after your changes related to `dynamic` keyword and fixed potential bugs related to obfuscation.

2021-06-27 15:24 UTC, KvanTTT commented
Done. Also, I fixed the renaming bug after your changes related to `dynamic` and fixed some potential bugs related to reflection.

2021-07-02 09:32 UTC, mkaring approved these changes

2021-07-02 09:33 UTC, merged

2021-07-14 12:29 UTC, wmjordan commented
I found that after this commit, ConfuserEx created a much larger but broken output for my assembly.
When the broken output assembly was run, the runtime reported some methods were not found.

I will try to make a possible smaller project to reproduce related problems.

2021-07-14 12:35 UTC, wmjordan commented
I found that after this commit, ConfuserEx created a much larger but broken output for my assembly.
When the broken output assembly was run, the runtime reported some methods were not found.

I will try to make a possible smaller project to reproduce related problems.

2021-07-14 12:36 UTC, KvanTTT commented
> I will try to make a possible smaller project to reproduce related problems.

It would be great.

2021-07-14 12:39 UTC, wmjordan commented
I mean the assembly.
I used reversible renaming thus no symbols.map was generated.

2021-07-14 12:41 UTC, KvanTTT commented
Does it work with the specified `shortNames` option?

2021-07-14 12:48 UTC, wmjordan commented
Not tried that option yet.

2021-07-14 15:29 UTC, KvanTTT commented
Please try. It's important to find out does it break assembly?

2021-07-15 00:34 UTC, wmjordan commented
Well, I downloaded the artifact and used it to process my assembly without the `shortNames` option.
I ran the output and the runtime reported a `System.BadImageFormatException` that there was a duplicated type `JqLoWOMO_NHYI5jO_oKtDdg`.

I inspected the assembly and found up to four of them:
![image](https://user-images.githubusercontent.com/12182730/125708960-e1b58572-8c7e-4c11-8792-b5a0fd4b4eee.png)

I decoded the name and found that it was not prefixed with the namespace. Yet other types are prefixed with their namespaces if they are decoded.

Originally, those four types were of the same name, but from various namespaces.
And each of them had at least a member annotated with the attribute
````C#
[Obfuscation(Exclude = false, Feature = "-rename")]
````

2021-07-15 00:56 UTC, wmjordan commented
I managed to reproduce the problem.
Please use the attached configuration and assembly.

[sample.zip](https://github.com/mkaring/ConfuserEx/files/6819643/sample.zip)