Implement ParamDef copy
mkaring/ConfuserEx pull request #366
Opened 2021-06-17 15:33 UTC by oSumAtrIX

2021-06-17 15:43 UTC, mkaring requested changes
Where does this oversight cause an error? As far as I am aware, none of the runtime code that is injected requires these to be present.

2021-06-17 15:43 UTC, mkaring commented on Confuser.Core/Helpers/InjectHelper.cs
> +               			newMethodDef.ParamDefs.Add(new ParamDefUser(paramDef.Name, paramDef.Sequence));
Please watch out for the indention. Only a single tab to indent the loop.
In addition the attributes of the Parameters should be copied as well, if we start with that.
```suggestion
               		newMethodDef.ParamDefs.Add(new ParamDefUser(paramDef.Name, paramDef.Sequence, paramDef.Attributes));
```

2021-06-17 16:44 UTC, oSumAtrIX commented on Confuser.Core/Helpers/InjectHelper.cs
> +               			newMethodDef.ParamDefs.Add(new ParamDefUser(paramDef.Name, paramDef.Sequence));
ParamDefs are not required per se and no error appears at runtime ,but they should be included for the sake of completeness

2021-06-18 18:02 UTC, ElektroKill requested changes

2021-06-18 18:02 UTC, ElektroKill commented on Confuser.Core/Helpers/InjectHelper.cs
> +               		newMethodDef.ParamDefs.Add(new ParamDefUser(paramDef.Name, paramDef.Sequence, paramDef.Attributes));
Mixed indent style! (tabs and spaces in the same line)

2021-06-18 18:12 UTC, oSumAtrIX reviewed
Fix idention style

2021-06-18 18:12 UTC, oSumAtrIX commented on Confuser.Core/Helpers/InjectHelper.cs
> +               		newMethodDef.ParamDefs.Add(new ParamDefUser(paramDef.Name, paramDef.Sequence, paramDef.Attributes));
```suggestion
				newMethodDef.ParamDefs.Add(new ParamDefUser(paramDef.Name, paramDef.Sequence, paramDef.Attributes));
```

2021-06-19 07:57 UTC, mkaring commented
Nice try fixing that complex method warning. :wink: The method is still too long for Codefactor to like it.

I noticed that the bracket style of your code doesn't line up with the rest of the code. Opening brackets are usually on the same line. For that not to happen, I got a `.editorconfig` setup in the project. I'm curious why that one isn't working for you.

2021-07-02 09:34 UTC, mkaring approved these changes

2021-07-02 09:35 UTC, merged