Renaming improvements
mkaring/ConfuserEx pull request #384
Opened 2021-07-20 12:22 UTC by KvanTTT

* Decrease size for output assemblies if reversible renaming mode is used (use compressed prefixes instead of full names for declaring types)
* Decrease size for output identifiers (drop return type for all members)

2021-07-24 17:04 UTC, KvanTTT commented
@wmjordan, please check the version from the current build: https://ci.appveyor.com/project/mkaring/confuserex/builds/40116594/artifacts Output size for `reversible` mode should be much smaller.

2021-07-25 01:41 UTC, wmjordan commented
It is amazing. I just used it.
The output  of my project is working well after this version, and its file size was even smaller than those before #305!

2021-07-25 10:09 UTC, KvanTTT commented
Yes, it can be because of the additional compressing of nested classes.

2021-07-25 17:59 UTC, mkaring requested changes
Something went wrong with the indentation of the code file at one spot. Other than that it's good work and will be merged.

2021-07-25 17:59 UTC, mkaring commented on Confuser.Renamer/NameService.cs
> +			public void SetParam(IDnlibDef def, string name, string value) {
The indention seems to be off here.

2021-07-28 14:58 UTC, mkaring approved these changes

2021-07-28 14:59 UTC, merged