Sequential renaming and performance improvements
mkaring/ConfuserEx pull request #401
Opened 2021-08-21 21:19 UTC by KvanTTT

I tried to reduce `FindDefinitions` calls in the pipeline and it seems working at least for me.

But more testing would be useful.

2021-08-21 21:28 UTC, KvanTTT commented on Confuser.Renamer/NameService.cs
> +		}
Maybe extract this to the new class `SequentialRenamer` similar to `ReversibleRenamer`? The same for `decodable`  and other renamers. Currently `NameService` does too much.

2021-08-22 07:16 UTC, mkaring commented
While good for the performance, this change is a _really_ bad idea. The problem is, that due to this change the protections that follow each other can't pick up new injected methods anymore. Also methods that got removed remain in that list.

2021-08-22 19:02 UTC, KvanTTT commented
Ok, I restored the previous behaviour but removed delegates because there is no reason to use them. Also added some microoptimizations.

2021-08-29 09:32 UTC, mkaring requested changes
I had a long look over this PR now, and I will not merge it.
There are so many unrelated and style changes in this PR, it will make any merges up to the 2.0 branch exceedingly difficult.

In addition to that many changes are actually making the code slower and increase the pressure on the garbage collection due to additional arrays that are just there for the sake of using insert range methods instead of separate add calls.

Please isolate the required change for the sequential renaming, the other changes will not be merged.

2021-08-29 09:32 UTC, mkaring commented on Confuser.Core/ConfuserEngine.cs
> +				asmResolver.PostSearchPaths.InsertRange(0,
This changes resulting order of the paths that are inserted into the search paths. Is that intentional?

2021-08-29 09:32 UTC, mkaring commented on Confuser.Core/Helpers/MutationHelper.cs
> +						var firstArgIndex = initialLoadInstructions.Min(instruction =>
Any reason for not simply passing the reference to the method on here?
```suggestion
						var firstArgIndex = initialLoadInstructions.Min(method.Body.Instructions.IndexOf);
```

2021-08-29 09:32 UTC, mkaring commented on Confuser.Core/Utils.cs
> +		public static void RemoveLast<T>(this List<T> self) => self.RemoveAt(self.Count - 1);
The parameter here can be widened to `IList`, to match the other extension methods.
```suggestion
		public static void RemoveLast<T>(this IList<T> self) => self.RemoveAt(self.Count - 1);
```

2021-08-29 09:32 UTC, mkaring commented on Confuser.Core/Utils.cs
> +		public static int RemoveAndInsertRange<T>(this IList<T> self, int index, int removingCount, IEnumerable<T> collection) {
I do not really like this method. It does two things at once. There is no real advantage of using it, instead of calling remove and insert separately.

2021-08-29 09:32 UTC, mkaring commented on Confuser.Protections/ReferenceProxy/StrongMode.cs
> +				cctor.Body.Instructions.InsertRange(0, new [] {
Showing the proper order of the instructions in code is a good idea, but that can be just as easily done by inserting into index 0, 1, 2 instead of allocating an additional array.

2021-08-29 10:07 UTC, KvanTTT commented on Confuser.Protections/TypeScrambler/Scrambler/Rewriter/Instructions/MemberRefInstructionRewriter.cs
> +				var instructions = new[] {
But the sequence of `Insert` methods work also not optimal for linear lists because each `Insert` call shifts the entire trailing part of the list.

2021-08-29 10:10 UTC, KvanTTT commented on Confuser.Core/ConfuserEngine.cs
> +				asmResolver.PostSearchPaths.InsertRange(0,
Not intentional.

2021-08-29 10:16 UTC, KvanTTT commented
Ok, I'll drop controversial performance and style changes. Moreover, they are not on a hot path, thus affect performance not significantly.

2021-08-29 10:17 UTC, KvanTTT commented on Confuser.Core/Utils.cs
> +		public static int RemoveAndInsertRange<T>(this IList<T> self, int index, int removingCount, IEnumerable<T> collection) {
I extracted such a method because it's used in several places.

2021-09-02 22:56 UTC, closed without merging